/* ----------------------------------------------------------------------------
 * Global constants for all DIV DLLs.
 * (C) VisualStudioEX3, José Miguel Sánchez Fernández - 2022
 * DIV Games Studio 2 (C) Hammer Technologies - 1998, 1999
 * ---------------------------------------------------------------------------- */

#ifndef __GLOBAL_CONSTANTS_H_
    #define __GLOBAL_CONSTANTS_H_

    // Defines a bool type, based on integer value:
    #define bool            int

    // Defines the default value for true state:
    #define true            1
    // Defines the default value for false state:
    #define false           0

    // Defines the default value for a successfull result:
    #define RESULT_OK       0
    // Defines the default value for an error result:
    #define RESULT_ERROR    -1
#endif
